### ISSUE TITLE
Buttons changing the metrics display with question marks

### ISSUE THREAD

**Issue by gkarag** [hmarr/vitals#13]
First thanks for your effort to create such a compact and useful utility!

I am using it with macOS Catalina. In version 0.5 there are two buttons supposed to change what metrics display and they work, but they both show question marks indicating the font used in this version of macOS doesn't have them.
![Screen Shot 2021-07-19 at 01 35 17](https://user-images.githubusercontent.com/3536866/126085593-bf23940f-e62a-4a99-8f71-037e4e76c843.png)

**Comment by hmarr** [comment]
Thanks for reporting this! I think I've [fixed](https://github.com/hmarr/vitals/commit/8a9ec7b14a45a8d4ccb5dbd257b39fcad1cfd0c6) the issue by bundling the icons used in the app – I didn't realise they were coming from an icon font on my computer.

I published a new release ([v0.6](https://github.com/hmarr/vitals/releases/tag/v0.6)) that includes the fix. Would you mind checking if the new release fixes the issue, as it's a little hard to reproduce on my computer?

To get the new release, you can download the app from the [GitHub release](https://github.com/hmarr/vitals/releases/tag/v0.6) or install from my [homebrew tap](https://github.com/hmarr/homebrew-tap) (`brew tap hmarr/tap && brew install hmarr/tap/vitals`). Once I know it does the job I'll update the official hombrew release.

**Comment by hmarr** [comment]
v0.6 is now available in the main homebrew repository, so installing from there should also work (`brew update && brew upgrade vitals`).

**Comment by gkarag** [comment]
Thanks for the quick response! I have installed v0.6 and the buttons look much better 👍🏼 
![Screen Shot 2021-07-19 at 23 48 04](https://user-images.githubusercontent.com/3536866/126231843-bf5bedc6-06e1-4f6f-8267-cd3d78a7693a.png)
