### ISSUE TITLE
Sometimes hang when switching between pages

### ISSUE THREAD

**Issue by garyemerson** [hmarr/vitals#15]
(really enjoy using the app when I have to btw. Thanks, for making and sharing it!)

### Description

Sometimes when clicking to switch to a different resource page the app hangs and the infamous spinning wheel appears. Interestingly, all that is required to "unhang" is to move the cursor and the app will instantly become responsive again and switch resource pages (see video for more clear demo).

### Steps to reproduce

1. Click thru resource pages without moving the cursor, just clicking
2. Take note of the resource heading label (e.g. "CPU", "Memory" etc) and when you see that the page hasn't change but you have clicked then wait a few seconds and observe the spinning wheel and the page never changing
3. Move cursor and observe spinning wheel disappearing and resource page changing appropriately

### Environment

* Vitals version 0.7
* Device: MacBook Air (Retina, 13-inch, 2018)
* OS version: macOS Monterey 12.0.1 (21A559)

### Video demo

(please excuse the annoying popup for the trial software I downloaded to show my mouse clicks)

https://user-images.githubusercontent.com/5726308/141922180-15a24ac5-f480-4e76-8b6e-c18e68bb1a58.mp4

### Instruments trace

I also recorded a trace using the instruments app while repro'ing this issue and attached it below. If you open it in instruments you can see when the "spinning" event happened and what function calls were most present in the samples. Lots of things to do with mouse events and it doesn't look like the CPU usage is very high so it might be erroneously waiting on an event.

[vitals.trace.zip](https://github.com/hmarr/vitals/files/7543477/vitals.trace.zip)

**Comment by hmarr** [comment]
Thanks for the detailed issue! This has been a problem for me too. I _think_ this was happening because the stats collection was (unintentionally) happening on the main thread. [v0.8](https://github.com/hmarr/vitals/releases/tag/v0.8) moves the stats collection to a background thread, which seems to fix this, at least in my testing.
