### ISSUE TITLE
Add a "kill process" button

### ISSUE THREAD

**Issue by hmarr** [hmarr/vitals#4]
I quite often end up killing CPU hogs after I've tracked them down. It'd be nice to be able to do that right from Vitals.

**Comment by hmarr** [comment]
I have no near-term plans to do this, so closing it out.

**Comment by brechtm** [comment]
I just wanted to add my +1 here, as this would be very useful. A simple implementation could kill the application on a left-click (after confirmation?), or force-kill on shift + left-click.
