### ISSUE TITLE
List appears clipped at the top

### ISSUE THREAD

**Issue by ianh** [hmarr/vitals#7]
See attached screenshot.  I believe (according to the output of `top -ocpu`) that this top sparkline is for WindowServer.

<img width="472" alt="Screen Shot 2021-03-22 at 18 48 08" src="https://user-images.githubusercontent.com/114075/112080615-8c6baf00-8b3f-11eb-8c6f-e037541f0732.png">

**Comment by hmarr** [comment]
Thanks for reporting. Which version of macOS are you using? I've only been able to test it on Catalina so far.

**Comment by ianh** [comment]
Ah yeah, it's Big Sur 11.2.2 (20D80).  I looked at it in Xcode and it does look like the `VStack` is somehow larger than the `ContentView` that contains it.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/114075/112082709-0c474880-8b43-11eb-91ce-6336d71a0951.png">

**Comment by ianh** [comment]
Wrapping everything in a scroll view fixes the issue and looks nice too.  I created a pull request at #8 if you're interested!

**Comment by hmarr** [comment]
Thanks for looking into this! Good to know that the scroll view fixes it. I think I'd rather avoid scrolling if possible, given that the 20 items should all easily fit in the space available.

I wonder whether wrapping the `VStack` in anything else (`List`, `View`, etc) helps the situation. The two other things that come to mind are adjusting the padding on the `VStack`, and changing the [popover's `contentSize`](https://github.com/hmarr/vitals/blob/845a31de63b9dde61351db1a4abb7d68c119805d/Vitals/AppDelegate.swift#L26).

If you have a chance to try those out and they do the trick, please do submit a PR! But no pressure 😄 

Additionally, I noticed the numbers on the right look a bit smaller than the process names on the left. I'm not sure why that's happening for you – the other [Big Sur screenshot](https://twitter.com/shelikavoid/status/1374080754959912963) I've seen doesn't seem to exhibit that behaviour.

**Comment by ianh** [comment]
Sounds good, thanks for taking a look.  It seems like changing the `contentSize` of the popover so its height matches its contents would be a good solution, but I can't figure out how to get the height information out of SwiftUI.

**Comment by jlledo** [comment]
I've gone ahead and implemented the fix @ianh suggested in PR #10, hard coded since the height can be statically decided. As I mentioned in the PR this introduces a bit of coupling, but I really can't think of any other fix.

Before settling on that I basically tested every combination of calling fixedSize(horizontal:vertical:) on the Views, but nothing seemed to work. Granted, I'm no SwiftUI expert so feel free to reject if you don't think it's appropriate.

**Comment by ianh** [comment]
Verified this is fixed for me in b37168e.  Thanks!

**Comment by hmarr** [comment]
Great! I just published [v0.3](https://github.com/hmarr/vitals/releases/tag/v0.3) which includes this fix. It's also available in the Homebrew tap.
