### ISSUE TITLE
CPU usage for certain processes doesn't match Activity Monitor

### ISSUE THREAD

**Issue by nickrw** [hmarr/vitals#9]
See this example:

![image](https://user-images.githubusercontent.com/38138/112365197-48a7af80-8ccf-11eb-9936-28d437ec7b43.png)

`Google Chrome Helper (Renderer)` displays 36% but vitals shows a steady 7%. I watched it for some time and both numbers stayed roughly stable.

Running macOS 11.2.2

**Comment by hmarr** [comment]
I think it's possible that's a different Chrome helper process and you're running into https://github.com/hmarr/vitals/issues/7. 

https://github.com/hmarr/vitals/issues/7 is a pretty critical issue for Big Sur as it seems to be hiding literally the most important row in the table (the top one!) Unfortunately I'm locked to Catalina right now so have no ability to reproduce it.

**Comment by hmarr** [comment]
When you get a second can you try [v0.3](https://github.com/hmarr/vitals/releases/tag/v0.3) and see if that fixes it?

**Comment by nickrw** [comment]
I upgraded via homebrew and now vitals doesn't seem to start (or at least, it is missing from my menu bar). Are there any useful logs I could dig out?

**Comment by hmarr** [comment]
Yikes!

There might be some logs in the Console app?

You'll need to relaunch it after reinstalling it – could it be a Gatekeeper issue? You could double check that by right-clicking it in Finder then selecting "Open". If that is the problem I'll probably just give in and pay Apple for a proper developer account so I can get the app notarised and remove that warning.

**Comment by nickrw** [comment]
Hm, possibly I was just going mad, but it seems to be working (and I'm no longer seeing the symptoms reported in #7). I'll need to get on another google meet before I can confirm the chrome helper utilisation looks the same 😄

**Comment by hmarr** [comment]
Hah, let me know how you get on with google meet! Glad to hear #7 is fixed.

**Comment by nickrw** [comment]
Looks like this was the fix 🎉

**Comment by hmarr** [comment]
🥳
